version: "3.4"
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
    networks:
      - practice-network
    volumes: 
      # - ~/static:/static
      - ~/staticFiles:/root/staticFiles
    restart: always

  backend:
    build:
      context: ./server
    container_name: backend
    hostname: backend
    ports:
      - "8443:8000"
      - "8000:8000"
    depends_on:
      - mongo
      - db
    networks:
      - practice-network
    restart: always
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - practice-network
    restart: always
  client:
    build:
      context: ./client
    container_name: client
    hostname: client
    networks:
      - practice-network
    ports:
      - "3000:3000"
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    hostname: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - practice-network

networks:
  practice-network:
    
     
